name: 'FindPlayer'
version: '${project.version}'
authors: ['PenalBuffalo']
description: '${project.description}'

softdepend: ['WorldGuard', 'PlaceholderAPI']

main: 'me.stumper66.findplayer.FindPlayer'
api-version: '1.13'

commands:
  findp:
    description: This command returns a player's coordinates. If configured with logging it will also store player's coordinates when they are offline.
    usage: /findp [filter|player|reload|purge|info]

permissions:
  FindPlayer.*:
    description: 'all findplayer permissions'
    default: op
    children:
      FindPlayer.player: true
      FindPlayer.reload: true
      FindPlayer.purge: true
  FindPlayer.player:
    description: access to /FindPlayer player [playername]
    default: op
  FindPlayer.reload:
    description: access to /FindPlayer reload
    default: op
  FindPlayer.purge:
    description: access to /FindPlayer purge
    default: op 